(defsystem "naive-sort-test"
  :author "Generated by GitHub Copilot"
  :license "MIT"
  :description "Tests for naive-sort"
  :depends-on ("naive-sort"
               "fiveam")
  :components ((:module "test"
                :components
                ((:file "naive_sort_test"))))
  :perform (test-op (op c) (symbol-call :fiveam :run! :naive-sort-suite)))