(defsystem "naive-sort"
  :author "Generated by GitHub Copilot"
  :license "MIT"
  :description "Naive sorting algorithms implementation in Common Lisp"
  :depends-on ("alexandria")
  :components ((:module "src"
                :components
                ((:file "naive-sort")))))